services:
  - type: web
    name: masareefi
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: MASAREEFI
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: masareefi
          property: host
      - key: APP_URL
        value: https://masareefi.onrender.com
      - key: ASSET_URL
        value: https://masareefi.onrender.com    
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "26817"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        value: /var/www/html/docker/aiven-ca.pem
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
    healthCheckPath: /